import _ from 'lodash';
import {
  body, sanitizeParam, param, sanitizeBody,
} from 'express-validator';
import validate from 'routes/middlewares/verifyInput';

function isExtrictedObject(val) {
  if (val === null) return false;
  return _.isObject(val) && !_.isArray(val);
}

function sanitizeToCreate(model, values) {
  Object.keys(values)
    .filter(field => Array.isArray(values[field]))
    .forEach((field) => {
      const assocModel = model.associations[field].target;
      values[field] = values[field].map(assocVals => sanitizeToCreate(assocModel, assocVals));
    });

  Object.keys(values)
    .filter(field => isExtrictedObject(values[field]))
    .forEach((field) => {
      const assocModel = model.associations[field].target;
      values[field] = sanitizeToCreate(assocModel, values[field]);
    });
  return _.omit(values, model.autoGeneratedFields());
}

function sanitizeToUpdate(model, values) {
  Object.keys(values)
    .filter(field => Array.isArray(values[field]))
    .forEach((field) => {
      const assocModel = model.associations[field].target;
      values[field] = values[field].map(assocVals => sanitizeToUpdate(assocModel, assocVals));
    });

  Object.keys(values)
    .filter(field => isExtrictedObject(values[field]))
    .forEach((field) => {
      const assocModel = model.associations[field].target;
      values[field] = sanitizeToUpdate(assocModel, values[field]);
    });
  return _.omit(values, [...model.unupdateFields(), 'createdAt', 'updatedAt', 'deletedAt']);
}

export default function (router, controller, model, options = {}) {
  const { methods } = options;

  if (!methods || methods.includes('getAll')) {
    router.get('/', async (req, res, next) => {
      try {
        const instances = await controller.getAll();
        return res.status(200).send(instances);
      } catch (e) {
        return next(e);
      }
    });
  }

  if (!methods || methods.includes('getById')) {
    router.get(
      '/:id(\\d+)/',
      sanitizeParam('id').toInt(),
      validate([[param('id').custom(id => model.verifyPk(id)), 404]]),
      async (req, res, next) => {
        try {
          const { id } = req.params;
          const instance = await controller.getById(id);
          return res.status(200).send(instance);
        } catch (e) {
          return next(e);
        }
      },
    );
  }

  if (!methods || methods.includes('create')) {
    router.post(
      '/',
      sanitizeBody().customSanitizer(values => sanitizeToCreate(model, values)),
      validate([body().custom(values => model.validate(values))]),
      async (req, res, next) => {
        try {
          const instance = await controller.create(req.body);
          return res.status(201).send(instance);
        } catch (e) {
          return next(e);
        }
      },
    );
  }

  if (!methods || methods.includes('update')) {
    router.patch(
      '/:id',
      sanitizeParam('id').toInt(),
      sanitizeBody().customSanitizer(values => sanitizeToUpdate(model, values)),
      validate([[param('id').custom(id => model.verifyPk(id)), 404]]),
      async (req, res, next) => {
        try {
          console.log(req.body);
          const instance = await controller.update(req.params.id, req.body);
          return res.status(200).send(instance);
        } catch (e) {
          return next(e);
        }
      },
    );
  }

  if (!methods || methods.includes('remove')) {
    router.delete(
      '/:id',
      sanitizeParam('id').toInt(),
      validate([[param('id').custom(id => model.verifyPk(id)), 404]]),
      async (req, res, next) => {
        try {
          const instance = await controller.remove(req.params.id);
          return res.status(200).send(instance);
        } catch (e) {
          return next(e);
        }
      },
    );
  }
}
