import { isExtrictedObject } from 'helpers/object';
import { capitalize } from 'helpers/string';
import { getErrorVerifyPk } from './validate';

export async function upsert(model, values) {
  if (!isExtrictedObject(values)) return model.findByPk(values);
  if (!values.id) return model.create(values);
  const instance = await model.findByPk(values.id);
  return instance.update(values);
}

export function manyUpsert(model, values) {
  return Promise.all(values.map(val => upsert(model, val)));
}

export async function fullUpdate(model, id, body) {
  const instance = await model.findByPk(id);
  const allPromisses = Object.keys(model.associations).map(async (asscKey) => {
    if (body[asscKey]) {
      const result = await manyUpsert(model.associations[asscKey].target, body[asscKey]);
      await instance[`set${capitalize(asscKey)}`](result);
      return 1;
    }
    return 0;
  });

  await Promise.all(allPromisses);

  return instance.update(body);
}

async function updateAssoc(values, fieldName, id, model) {
  let result = null;
  if (Array.isArray(values)) {
    const assocBody = values.map(x => ({
      ...x,
      [fieldName]: id,
    }));
    result = await manyUpsert(model, assocBody);
  } else {
    const assocBody = { ...values, [fieldName]: id };
    result = await upsert(model, assocBody);
  }
  return result;
}

export async function fullCreate(model, body) {
  const instance = await model.create(body);
  const allPromisses = Object.keys(model.associations).map(async (asscKey) => {
    if (!body[asscKey]) return 0;

    const assocModel = model.associations[asscKey].target;
    const referenceFields = Object.values(assocModel.rawAttributes).filter(
      field => field.references && field.references.model === model.name,
    );

    if (referenceFields.length === 1) {
      const result = updateAssoc(
        body[asscKey],
        referenceFields[0].fieldName,
        instance.id,
        assocModel,
      );
      await instance[`set${capitalize(asscKey)}`](result);
    }
    return 1;
  });

  await Promise.all(allPromisses);

  return instance.update(body);
}

export async function verifyPk(model, id) {
  const error = await getErrorVerifyPk(model, id);
  if (error !== null) throw new Error(error);
}

export function autoGeneratedFields(model) {
  return (
    Object.values(model.rawAttributes)
      // eslint-disable-next-line no-underscore-dangle
      .filter(field => field._autoGenerated)
      .map(field => field.fieldName)
  );
}

export function unupdateFields(model) {
  return Object.values(model.rawAttributes)
    .filter(field => field.canUpdate === false)
    .map(field => field.fieldName);
}
